### ISSUE TITLE
Handling of string args with embedded spaces

### ISSUE THREAD

**Issue by meekj** [songgao/flags.hh#1]
This is a great lightweight alternative to Boost program_options, however I need to supply strings with embedded spaces which does not seem to be supported:

example --str 'dst port 3000'
var1: 64
var2: 32
var3: 42
str:  dst     <-- only first word is picked up
b:    unset

Thanks,

Jon

**Comment by songgao** [comment]
Hi @meekj , good catch, thanks!

I've pushed a fix. Could you try it?

**Comment by meekj** [comment]
Fantastic quick response ! It works!

Now I will undo my revert to Boost and be close putting my new code on
GitHub. An additional help is that I used the same license as you and
libpcap (which my code uses) so I don't have figure out if there is a
conflict.

Thanks,

Jon

**Comment by songgao** [comment]
Glad to know it helps, and congrats on being close to finishing your project :D
